repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      #      - id: pretty-format-json
      - id: check-ast
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: no-commit-to-branch
        args: [ --branch, main, --pattern, production/.* ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: python manage.py makemigrations --check --dry-run
        language: system
        types: [ python ]
        pass_filenames: false
