version: '3.7'

x-backend-service: &x-backend-service
  image: briler/second-brain:latest
  env_file:
    - .env
  restart: unless-stopped
  volumes:
    - static_volume:/app/static
  labels:
    - "com.centurylinklabs.watchtower.enable=true"
  depends_on:
    - postgres
    - redis
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
    interval: 30s
    timeout: 10s
    retries: 3

services:

  migrate:
    <<: *x-backend-service
    command: python manage.py migrate --noinput && python manage.py seeds && python manage.py collectstatic --clear
    restart: "no"

  backend:
    <<: *x-backend-service
    expose:
      - 8000
    command: [ "gunicorn", "-c", "/app/app/gunicorn.py", "app.wsgi" ]

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/static/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/admin" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  #  telegram-bot-webhook:
  #    <<: *x-backend-service
  #    expose:
  #      - 8000
  #    command: python manage.py run_telegram_webhook

  # uncomment if you want to use pooling instead of webhook
  telegram-bot-pooling:
    <<: *x-backend-service
    command: python manage.py run_telegram_polling

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.lifecycle.post-update=./bin/restart_all.sh"

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  celery:
    <<: *x-backend-service
    command: celery -A app worker --loglevel=debug --beat --scheduler=django_celery_beat.schedulers:DatabaseScheduler

volumes:
  postgres_data:
  static_volume:
  redis_data:
