# Generated by Django 5.1.2 on 2025-02-24 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'side',
                    models.CharField(
                        choices=[
                            ('short', 'Short'),
                            ('long', 'Long'),
                            ('spot', 'Spot'),
                            ('margin-short', 'Margin Short'),
                            ('margin-long', 'Margin Long'),
                        ]
                    ),
                ),
                ('open_price', models.DecimalField(decimal_places=16, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=16, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=16, max_digits=20)),
                ('leverage', models.IntegerField(default=1)),
                ('fees', models.DecimalField(decimal_places=16, max_digits=20)),
                ('funding', models.DecimalField(decimal_places=16, max_digits=20)),
                ('is_liquidated', models.BooleanField(default=False)),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trades', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Trading Pair',
                'verbose_name_plural': 'Trading Pairs',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='arbitrage_deals',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
                (
                    'long',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='long_deal',
                        to='arbitrage.arbitragedealitem',
                        verbose_name='Long Deal',
                    ),
                ),
                (
                    'short',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='short_deal',
                        to='arbitrage.arbitragedealitem',
                        verbose_name='Short Deal',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Arbitrage Deal',
                'verbose_name_plural': 'Arbitrage Deals',
            },
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='exchange',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_deal', to='arbitrage.exchange'
            ),
        ),
        migrations.CreateModel(
            name='ExchangeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('_api_secret', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                (
                    'exchange',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credentials',
                        to='arbitrage.exchange',
                        verbose_name='Exchange',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='arbitrage_exchanges',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exchange Credentials',
                'verbose_name_plural': 'Exchange Credentials',
            },
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.tradingpair'),
        ),
    ]
