# Generated by Django 5.1.2 on 2025-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='close_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='fees',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='funding',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='open_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
