# Generated by Django 5.1.2 on 2025-02-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0002_alter_arbitragedealitem_close_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitragedeal',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
