# Generated by Django 5.1.2 on 2025-02-25 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0003_arbitragedeal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='arbitragedeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='arbitragedeal',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='arbitragedeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Close At'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='close_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='exchange',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arbitrage_deal',
                to='arbitrage.exchange',
                verbose_name='Exchange',
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='fees',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='funding',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='is_liquidated',
            field=models.BooleanField(default=False, verbose_name='Is Liquidated'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='leverage',
            field=models.IntegerField(default=1, verbose_name='Leverage'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='open_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Open At'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='open_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Open Price'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='side',
            field=models.CharField(
                choices=[
                    ('short', 'Short'),
                    ('long', 'Long'),
                    ('spot', 'Spot'),
                    ('margin-short', 'Margin Short'),
                    ('margin-long', 'Margin Long'),
                ],
                verbose_name='Side',
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='trades',
            field=models.JSONField(blank=True, null=True, verbose_name='Trades'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='trading_pair',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='arbitrage.tradingpair', verbose_name='Trading Pair'
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='exchangecredentials',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='exchangecredentials',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is Enabled'),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='base_currency',
            field=models.CharField(max_length=10, verbose_name='Base Currency'),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='quote_currency',
            field=models.CharField(max_length=10, verbose_name='Quote Currency'),
        ),
    ]
