# Generated by Django 5.1.2 on 2025-02-25 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0004_exchange_created_at_exchange_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitragedealitem',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arbitrage_deals_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
            preserve_default=False,
        ),
    ]
