# Generated by Django 5.1.2 on 2025-02-25 05:20

from decimal import Decimal

from django.db import migrations, models

from arbitrage.models import ArbitrageDealItem


def update(*args, **kwargs):
    for a in ArbitrageDealItem.objects.all():
        a.save()


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0005_arbitragedealitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitragedealitem',
            options={'verbose_name': 'Arbitrage Deal Item', 'verbose_name_plural': 'Arbitrage Deal Items'},
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='exchanges',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Exchanges'),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='fees',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Fees'),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='funding',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Funding'),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='income',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Income'),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='margin_close',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Close'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='margin_open',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Open'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='PnL'),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='roi',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI'),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='roi_percent',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI Percent'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='spread',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Spread (%)'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='spread_close',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Spread Close (%)'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='spread_open',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Spread Open (%)'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedeal',
            name='trading_volume',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Trading Volume'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='human_duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Human Duration'),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='income',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Income'),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='margin_close',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Close'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='margin_open',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Open'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='PnL'),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='roi',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI'),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='roi_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI %'),
        ),
        migrations.RunPython(update, lambda *args, **kwargs: None),
    ]
