# Generated by Django 5.1.2 on 2025-03-01 14:31

from django.db import migrations, models

from arbitrage.models import Exchange


def update(*args, **kwargs):
    for e in Exchange.objects.all():
        e.save()


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0006_alter_arbitragedealitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Symbol'),
        ),
        migrations.RunPython(update, lambda *args, **kwargs: None),
    ]
