# Generated by Django 5.1.2 on 2025-03-01 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0007_tradingpair_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragedeal',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arbitrage_deals',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arbitrage_deals_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
