# Generated by Django 5.1.2 on 2025-09-20 05:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0010_arbitragedeal_apr_percent_balance_balancesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitragedeal',
            name='type',
            field=models.CharField(
                choices=[('arbitrage', 'Arbitrage'), ('trade', 'Trade')],
                default='arbitrage',
                max_length=20,
                verbose_name='Deal Type',
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedeal',
            name='long',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='long_deal',
                to='arbitrage.arbitragedealitem',
                verbose_name='Long Deal',
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedeal',
            name='short',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='short_deal',
                to='arbitrage.arbitragedealitem',
                verbose_name='Short Deal',
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='close_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True, verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='fees',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='funding',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='leverage',
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Leverage'
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='volume',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Volume'),
        ),
    ]
