# Generated by Django 5.1.2 on 2025-09-21 01:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0011_arbitragedeal_type_alter_arbitragedeal_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitragedealitem',
            name='extra_margin',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Extra Margin'
            ),
        ),
        migrations.AddField(
            model_name='arbitragedealitem',
            name='trading_volume',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Trading Volume'
            ),
        ),
        migrations.AlterField(
            model_name='arbitragedealitem',
            name='close_price',
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Close Price'
            ),
        ),
    ]
