# Generated by Django 5.1.2 on 2025-09-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arbitrage', '0012_arbitragedealitem_extra_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragedeal',
            name='type',
            field=models.CharField(
                choices=[('arbitrage', 'Arbitrage'), ('hedge', 'Hedge'), ('trade', 'Trade')],
                default='arbitrage',
                max_length=20,
                verbose_name='Deal Type',
            ),
        ),
    ]
