# Generated by Django 4.2.9 on 2024-07-17 09:31

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(editable=False, max_length=50)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('planed', 'Planned'),
                            ('active', 'Active'),
                            ('success', 'Done'),
                            ('failed', 'Failed'),
                            ('canceled', 'Canceled'),
                        ],
                        default='active',
                        max_length=50,
                    ),
                ),
                (
                    'data',
                    models.JSONField(
                        default=dict,
                        editable=False,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ('debounced_till', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'touched_at',
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text='When last time is was ran. This helps to proceed jobs all round',
                    ),
                ),
                ('parents', models.ManyToManyField(editable=False, related_name='children', to='workflows.job')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_class', models.CharField(editable=False, max_length=150)),
                ('config_id', models.BigIntegerField(editable=False, null=True)),
                (
                    'data',
                    models.JSONField(
                        editable=False,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('done', 'Done'), ('failed', 'Failed')],
                        default='active',
                        max_length=50,
                    ),
                ),
                ('done_at', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'config_type',
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'process',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='logs',
                        to='workflows.process',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Process log',
                'verbose_name_plural': 'Process logs',
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='logs',
                        to='workflows.job',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Job log',
                'verbose_name_plural': 'Job logs',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='jobs',
                to='workflows.process',
            ),
        ),
    ]
