# Generated by Django 5.1 on 2024-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Data'),
        ),
    ]
