# Generated by Django 5.1 on 2024-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reminders', '0002_alter_reminder_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='task_class',
            field=models.CharField(
                choices=[('reminders.reminders_tasks.telegram_reminder.TelegramReminderTask', 'TelegramReminderTask')],
                max_length=200,
                verbose_name='Task Class',
            ),
        ),
    ]
