# Generated by Django 5.1 on 2024-09-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('reminders', '0003_alter_reminder_task_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='periodic_task',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reminders',
                to='django_celery_beat.periodictask',
                verbose_name='Periodic Task',
            ),
        ),
    ]
