# Generated by Django 5.1.2 on 2024-11-13 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('source_id', models.BigIntegerField(editable=False, null=True, verbose_name='Source ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')],
                        default='active',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                (
                    'tags',
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated tags for categorizing notes',
                        max_length=255,
                        verbose_name='Tags',
                    ),
                ),
                (
                    'related_notes',
                    models.ManyToManyField(
                        blank=True, related_name='related_notes', to='notes.note', verbose_name='Related Notes'
                    ),
                ),
                (
                    'source_type',
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='contenttypes.contenttype',
                        verbose_name='Source Type',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notes',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
