# Generated by Django 5.1.2 on 2025-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='related_notes',
            field=models.ManyToManyField(blank=True, to='notes.note', verbose_name='Related Notes'),
        ),
    ]
