# Generated by Django 5.1 on 2024-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0002_alter_course_position_alter_group_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='position',
            field=models.PositiveIntegerField(default=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='group',
            name='position',
            field=models.PositiveIntegerField(default=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(default=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='lessonentity',
            name='position',
            field=models.PositiveIntegerField(default=100, verbose_name='Position'),
        ),
    ]
