# Generated by Django 5.1 on 2024-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0004_learningprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogress',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Is Finished'),
        ),
    ]
