# Generated by Django 5.1 on 2024-09-24 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0005_learningprogress_is_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('position',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('position',), 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('position',), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonentity',
            options={
                'ordering': ('position',),
                'verbose_name': 'Lesson Entity',
                'verbose_name_plural': 'Lesson Entities',
            },
        ),
    ]
