# Generated by Django 5.1 on 2024-09-29 19:49

from django.db import migrations, models

import utils.helpers


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0008_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='position',
            field=utils.helpers.AutoIncrementalField(editable=False, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='group',
            name='position',
            field=utils.helpers.AutoIncrementalField(editable=False, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='timecode',
            field=models.BigIntegerField(default=0, verbose_name='Timecode (in seconds)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=utils.helpers.AutoIncrementalField(editable=False, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='lessonentity',
            name='position',
            field=utils.helpers.AutoIncrementalField(editable=False, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='link',
            name='position',
            field=utils.helpers.AutoIncrementalField(editable=False, verbose_name='Position'),
        ),
    ]
