# Generated by Django 5.1 on 2024-09-29 19:56

from django.db import migrations

import utils.helpers


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0009_alter_course_position_alter_group_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='position',
            field=utils.helpers.AutoIncrementalField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='group',
            name='position',
            field=utils.helpers.AutoIncrementalField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=utils.helpers.AutoIncrementalField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='lessonentity',
            name='position',
            field=utils.helpers.AutoIncrementalField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='link',
            name='position',
            field=utils.helpers.AutoIncrementalField(verbose_name='Position'),
        ),
    ]
