# Generated by Django 5.1.2 on 2025-10-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0010_alter_course_position_alter_group_position_and_more'),
        ('telegram_bot', '0006_file_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='thumbnail',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='group_thumbnails',
                to='telegram_bot.file',
                verbose_name='Thumbnail',
            ),
        ),
    ]
