# Generated by Django 5.1.2 on 2025-10-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0011_group_thumbnail'),
        ('telegram_bot', '0006_file_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='course_thumbnails',
                to='telegram_bot.file',
                verbose_name='Thumbnail',
            ),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lesson_thumbnails',
                to='telegram_bot.file',
                verbose_name='Thumbnail',
            ),
        ),
    ]
