# Generated by Django 5.1.2 on 2025-10-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0012_course_thumbnail_lesson_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='links',
                to='courses.course',
                verbose_name='Course',
            ),
        ),
        migrations.AddField(
            model_name='link',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='links',
                to='courses.group',
                verbose_name='Group',
            ),
        ),
        migrations.AddField(
            model_name='link',
            name='lesson',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='links',
                to='courses.lesson',
                verbose_name='Lesson',
            ),
        ),
        migrations.AlterField(
            model_name='link',
            name='lesson_entity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='links',
                to='courses.lessonentity',
                verbose_name='Lesson Entity',
            ),
        ),
    ]
