# Generated by Django 5.0.1 on 2024-01-14 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'content_type',
                    models.CharField(
                        choices=[
                            ('audio', 'audio'),
                            ('document', 'document'),
                            ('photo', 'photo'),
                            ('story', 'story'),
                            ('video', 'video'),
                            ('video_note', 'video_note'),
                            ('voice', 'voice'),
                            ('location', 'location'),
                        ],
                        max_length=200,
                        verbose_name='Content Type',
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('file_id', models.CharField(max_length=200, verbose_name='File ID')),
                ('thumbnail_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Thumbnail ID')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Raw Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Uploaded By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
