# Generated by Django 5.1 on 2024-09-02 09:10

from django.db import migrations, models

from telegram_bot.models import File


class Migration(migrations.Migration):
    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_unique_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='File Unique ID'),
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MIME Type'),
        ),
        migrations.RunSQL(
            sql=f"""
            UPDATE {File._meta.db_table}
            SET
                file_unique_id = COALESCE(raw_data->>'file_unique_id', file_unique_id),
                mime_type = COALESCE(raw_data->>'mime_type', mime_type)
            WHERE
                raw_data IS NOT NULL;
        """,
            reverse_sql=f"""
            UPDATE {File._meta.db_table}
            SET
                file_unique_id = NULL,
                mime_type = NULL
            WHERE
                raw_data IS NOT NULL;
        """,
        ),
    ]
