# Generated by Django 5.0.1 on 2024-01-14 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegram_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.CharField(
                choices=[
                    ('audio', 'audio'),
                    ('document', 'document'),
                    ('photo', 'photo'),
                    ('story', 'story'),
                    ('video', 'video'),
                    ('video_note', 'video_note'),
                    ('voice', 'voice'),
                    ('location', 'location'),
                ],
                max_length=200,
                verbose_name='Content Type',
            ),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(max_length=200, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='raw_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumbnail_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Thumbnail ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Uploaded By',
            ),
        ),
    ]
