# Generated by Django 5.1 on 2024-09-02 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('telegram_bot', '0002_file_file_unique_id_file_mime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='thumbnail_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
    ]
