# Generated by Django 5.1 on 2024-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegram_bot', '0005_alter_message_raw_data_alter_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Caption'),
        ),
    ]
