# Generated by Django 5.1 on 2024-09-02 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Prompt')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('voice_recognition', 'Voice Recognition'),
                            ('text_recognition', 'Text Recognition'),
                            ('task_recognition', 'Task Recognition'),
                        ],
                        max_length=50,
                        verbose_name='Category',
                    ),
                ),
                (
                    'time_spent',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name='Time Spent',
                    ),
                ),
                ('source_id', models.BigIntegerField(editable=False, null=True, verbose_name='Source ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                (
                    'source_type',
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='contenttypes.contenttype',
                        verbose_name='Source Type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
