# Generated by Django 5.1.2 on 2025-09-21 03:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10, verbose_name='Base Currency')),
                ('quote_currency', models.CharField(max_length=10, verbose_name='Quote Currency')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Trading Pair',
                'verbose_name_plural': 'Trading Pairs',
            },
        ),
        migrations.CreateModel(
            name='CryptoDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'side',
                    models.CharField(
                        choices=[
                            ('short', 'Short'),
                            ('long', 'Long'),
                            ('spot', 'Spot'),
                            ('margin-short', 'Margin Short'),
                            ('margin-long', 'Margin Long'),
                        ],
                        verbose_name='Side',
                    ),
                ),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Open Price')),
                (
                    'close_price',
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Close Price'
                    ),
                ),
                (
                    'volume',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Volume'
                    ),
                ),
                (
                    'leverage',
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Leverage'
                    ),
                ),
                (
                    'fees',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Fees'),
                ),
                (
                    'funding',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Funding'
                    ),
                ),
                ('is_liquidated', models.BooleanField(default=False, verbose_name='Is Liquidated')),
                ('open_at', models.DateTimeField(blank=True, null=True, verbose_name='Open At')),
                ('close_at', models.DateTimeField(blank=True, null=True, verbose_name='Close At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('trades', models.JSONField(blank=True, null=True, verbose_name='Trades')),
                (
                    'pnl',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='PnL'),
                ),
                (
                    'extra_margin',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Extra Margin'
                    ),
                ),
                (
                    'margin_open',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Open'
                    ),
                ),
                (
                    'margin_close',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Close'
                    ),
                ),
                (
                    'trading_volume',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Trading Volume'
                    ),
                ),
                (
                    'income',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Income'
                    ),
                ),
                (
                    'roi',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI'),
                ),
                (
                    'roi_percent',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI %'),
                ),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                (
                    'human_duration',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Human Duration'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='crypto_deals_items',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
                (
                    'exchange',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='crypto_deal',
                        to='crypto.exchange',
                        verbose_name='Exchange',
                    ),
                ),
                (
                    'trading_pair',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='crypto.tradingpair',
                        verbose_name='Trading Pair',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Crypto Deal Item',
                'verbose_name_plural': 'Crypto Deal Items',
            },
        ),
        migrations.CreateModel(
            name='CryptoDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'type',
                    models.CharField(
                        choices=[('arbitrage', 'Arbitrage'), ('hedge', 'Hedge'), ('trade', 'Trade')],
                        default='arbitrage',
                        max_length=20,
                        verbose_name='Deal Type',
                    ),
                ),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('exchanges', models.CharField(blank=True, default='', max_length=255, verbose_name='Exchanges')),
                (
                    'pnl',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='PnL'),
                ),
                (
                    'income',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Income'
                    ),
                ),
                (
                    'fees',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Fees'),
                ),
                (
                    'funding',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Funding'
                    ),
                ),
                (
                    'roi',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI'),
                ),
                (
                    'roi_percent',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='ROI Percent'
                    ),
                ),
                (
                    'spread_open',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Spread Open (%)'
                    ),
                ),
                (
                    'spread_close',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Spread Close (%)'
                    ),
                ),
                (
                    'spread',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Spread (%)'
                    ),
                ),
                (
                    'margin_open',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Open'
                    ),
                ),
                (
                    'margin_close',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Margin Close'
                    ),
                ),
                (
                    'trading_volume',
                    models.DecimalField(
                        decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Trading Volume'
                    ),
                ),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                (
                    'human_duration',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Human Duration'),
                ),
                (
                    'apr_percent',
                    models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='APR %'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='crypto_deals',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
                (
                    'long',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='long_deal',
                        to='crypto.cryptodealitem',
                        verbose_name='Long Deal',
                    ),
                ),
                (
                    'short',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='short_deal',
                        to='crypto.cryptodealitem',
                        verbose_name='Short Deal',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Crypto Deal',
                'verbose_name_plural': 'Crypto Deals',
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('asset', models.CharField(max_length=50)),
                ('free_snapshot', models.DecimalField(decimal_places=8, max_digits=20)),
                ('locked_snapshot', models.DecimalField(decimal_places=8, max_digits=20)),
                ('snapshot_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('asset', models.CharField(max_length=50)),
                ('free', models.DecimalField(decimal_places=8, max_digits=20)),
                ('locked', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key')),
                ('_api_secret', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                (
                    'exchange',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credentials',
                        to='crypto.exchange',
                        verbose_name='Exchange',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='crypto_exchanges',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exchange Credentials',
                'verbose_name_plural': 'Exchange Credentials',
            },
        ),
    ]
