name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          COMMIT_HASH=${{ github.sha }}
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/second-brain:latest --tag ${{ secrets.DOCKER_USERNAME }}/second-brain:${SHORT_SHA}

      - name: Push the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_USERNAME }}/second-brain:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/second-brain:${SHORT_SHA}
