# Generated by Django 5.1 on 2024-10-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegram_restricted_downloader', '0002_account_created_at_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telegram_id',
            field=models.BigIntegerField(null=True, verbose_name='Telegram ID'),
        ),
    ]
